export const ingredientIconMap = {
    "Butter": "./butter.png",
    "Eggs" : "./egg.png",
    "Cheese": "./cheese.png",
    "Carrot": "./carrot.png",
    "Yogurt": "./yogurt.svg",
    "Oil": "./oil.png",
    "Sheets filo pastry": "./filo-sheet-pastry.png",
    "Onion": "./onion.png",
    "Garlic": "./garlic.png",
    "Lentils": "./lentils.png",
    "Pepper": "./pepper.png",
    "Salt": "./salt.png",
    "Tomato": "./tomato.png",
    "Parsley": "./persley.png",
    "Olive oil": "./olive-oil.png",
    "Beef mince": "./minced-meat.png",
    "Spaghetti": "./pasta.png",
    "Potato": "./potato.png",
    "Aubergine": "./eggplant.png",
}