export const ingredientIconMap = {
    "Butter": "./butter.svg",
    "Eggs" : "./egg.svg",
    "Cheese": "./cheese.svg",
    "Carrot": "./carrot.svg",
    "Yogurt": "./yogurt.svg",
    "Oil": "./oil-olive.svg",
    "Sheets filo pastry": "./filo-sheet-pastry.png",
    "Onion": "./onion.svg",
    "Garlic": "./garlic.svg",
    "Lentils": "./lentils.png",
    "Pepper": "./pepper.svg",
    "Salt": "./salt.svg",
    "Tomato": "./tomato.svg",
    "Parsley": "./persley.jpg",
    "Olive oil": "./olive-oil.png",
    "Beef mince": "./minced-meat.png",
    "Spaghetti": "./pasta.png",
    "Potato": "./potato.svg",
    "Aubergine": "./aubergine.svg",
}