export const ingredientIconMap = {
    "Butter": "./butter-svgrepo-com.svg",
    "Eggs" : "./egg-svgrepo-com.svg",
    "Cheese": "./cheese-1-svgrepo-com.svg",
    "Carrot": "./carrot-svgrepo-com.svg",
    "Yogurt": "./ingredients/yogurt.svg",
    "Oil": "./ingredients/oil-olive.svg",
    "Sheets filo pastry": "./ingredients/filo-sheet-pastry.png",
    "Onion": "./ingredients/onion.svg",
    "Garlic": "./ingredients/garlic.svg",
    "Lentils": "./ingredients/lentils.png",
    "Pepper": "./ingredients/pepper.svg",
    "Salt": "./ingredients/salt.svg",
    "Tomato": "./ingredients/tomato.svg",
    "Parsley": "./ingredients/persley.jpg",
    "Olive oil": "./ingredients/olive-oil.png",
    "Beef mince": "./ingredients/minced-meat.png",
    "Spaghetti": "./ingredients/pasta.png",
    "Potato": "./ingredients/potato.svg",
    "Aubergine": "./ingredients/aubergine.svg",
}